pull request입니다
workromancer/java-chicken-2019 pull request #1
Opened 2019-12-29 06:03 UTC by lxxjn0

루피님 감사합니다 👍

2019-12-30 05:23 UTC, TheDevLuffy commented on README.md
> +# 오프라인 테스트 - java-chicken-2019
README 작성이 꼼꼼해서 보기 좋아요 👍

2019-12-30 05:24 UTC, TheDevLuffy commented on src/main/java/Application.java
> +            return getInputFunctionNumber();
재귀로 구현 했을 때 발생할 수 있는 문제점에 대해 생각해보시는 것도 좋을 것 같아요.

2019-12-30 05:28 UTC, TheDevLuffy commented on src/main/java/POS.java
> +    private final List<Function> functions = new ArrayList<>();
List 대신 Map 을 써보는 것은 어떨까요?

2019-12-30 05:31 UTC, TheDevLuffy commented on src/main/java/domain/Payment/OrderAmount.java
> +    public static OrderAmount ZERO = new OrderAmount(ZERO_ORDER_AMOUNT);
public static 으로 선언된 ``ZERO`` 변수가 사용되는 곳이 한 곳인데 더 적절한 위치로 옮길 수 있을 것 같아요~

2019-12-30 05:32 UTC, TheDevLuffy commented on src/main/java/domain/Payment/OrderAmount.java
> +        return new OrderAmount(this.orderAmount + addOrderAmount);
👍

2019-12-30 05:33 UTC, TheDevLuffy commented on src/main/java/domain/function/Function.java
> +public class Function {
``abstract`` 클래스에 대해 학습해보시는 것은 어떨까요?

2019-12-30 05:35 UTC, TheDevLuffy commented on src/main/java/domain/function/OrderFunction.java
> +        OutputView.printTables(tables);
비즈니스 로직을 담당하는 domain 객체의 메서드에서 View 의 역할도 같이 하고 있어요~
MVC 패턴에 대해 더 학습한 후 리팩토링 해보는 것은 어떨까요?

2019-12-30 05:40 UTC, TheDevLuffy commented on src/main/java/domain/function/OrderFunction.java
> +                .get();
Java 공부 하신지 얼마 되지 않으셨다고 하신 것으로 기억하는데 stream 사용까지 👏
Java8 의 Optional 에 대해 추가 학습해보시는 것은 어떨까요?

참고 링크 남겨드릴께요 !

https://www.daleseo.com/java8-optional-after/

2019-12-30 06:42 UTC, workromancer requested changes
안녕하세요~ 휴학생1님, 루피입니다. 🤠
코멘트 몇 개 남겨보았어요.
제 코멘트가 정답은 아닙니다 !
확인 해보시고 다른 방향으로 생각해보실 수 있는 기회가 되시면 좋겠습니다.
Function 객체를 만들어 POS 객체에서 사용하신 점은 매우 인상 깊네요.
피드백 확인하시고 궁금한 점 있으시면 코멘트 남겨주세요~

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/domain/function/PaymentFunction.java
> +                .get();
위에서 남긴 Optional 관련 코멘트 참고해주세요~

2019-12-30 06:42 UTC, TheDevLuffy commented on README.md
> +# 오프라인 테스트 - java-chicken-2019
README 작성이 꼼꼼해서 보기 좋아요 👍

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/Application.java
> +            return getInputFunctionNumber();
재귀로 구현 했을 때 발생할 수 있는 문제점에 대해 생각해보시는 것도 좋을 것 같아요.

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/POS.java
> +    private final List<Function> functions = new ArrayList<>();
List 대신 Map 을 써보는 것은 어떨까요?

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/domain/Payment/OrderAmount.java
> +    public static OrderAmount ZERO = new OrderAmount(ZERO_ORDER_AMOUNT);
public static 으로 선언된 ``ZERO`` 변수가 사용되는 곳이 한 곳인데 더 적절한 위치로 옮겨볼 수 있을 것 같아요~

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/domain/Payment/OrderAmount.java
> +        return new OrderAmount(this.orderAmount + addOrderAmount);
👍

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/domain/function/Function.java
> +public class Function {
``abstract`` 클래스에 대해 학습해보시는 것은 어떨까요?

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/domain/function/OrderFunction.java
> +        OutputView.printTables(tables);
domain(model) 으로 분류하신 객체의 메서드에서 View 의 역할도 같이 하고 있어요~
MVC 패턴에 대해 더 학습한 후 리팩토링 해보는 것은 어떨까요?

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/domain/function/OrderFunction.java
> +                .get();
Java 공부 하신지 얼마 되지 않으셨다고 하신 것으로 기억하는데 stream 사용까지 👏
Java8 의 Optional 에 대해 추가 학습해보시는 것은 어떨까요?

참고 링크 남겨드릴께요 !

https://www.daleseo.com/java8-optional-after/

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/domain/menu/Menu.java
> +        return category.isChicken();
👍

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/domain/menu/MenuQuantity.java
> +public class MenuQuantity {
주문 수량을 Wrapping 하는 객체를 통해 validation 하고 계신 것 👍

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/domain/table/Table.java
> +    private OrderAmount orderAmount = OrderAmount.ZERO;
생성자에서 초기화 해도 괜찮지 않을까요?

2019-12-30 06:42 UTC, TheDevLuffy commented on src/main/java/view/OutputView.java
> +    private static final String NON_COMPLETE_PAYMENT_BOTTOM_LINE = "└ \\ ┘";
``TABLE_FORMAT`` 을 참고 하신다면 주문이 완료된 테이블과 주문이 완료되지 않은 테이블을 하나의 문자열로 표현할 수 있지 않을까요?

2019-12-31 02:40 UTC, lxxjn0 commented on src/main/java/Application.java
> +            return getInputFunctionNumber();
나중에 확인해보니까 해당 코드를 실행 시, `InputMismatchException`이 발생하면 `null` 이라고 출력이 되더군요.

그래서 해당 코드를

```java
private static int getInputFunctionNumber() {
        try {
            final int functionNumber = InputView.inputFunctionNumber();
            return isValid(functionNumber);
        } catch (InputMismatchException | IllegalArgumentException e) {
            System.out.println("입력한 기능 목록이 존재하지 않습니다. 1부터 3까지의 숫자만 입력 가능합니다.");
            return getInputFunctionNumber();
        }
    }
```

이와 같이 예외 발생 출력메시지를 직접 넣도록 따로 수정해봤어요!

> 재귀로 구현 했을 때 발생할 수 있는 문제점에 대해 생각해보시는 것도 좋을 것 같아요.

위와 같은 try-catch문의 depth를 1로 줄일 수 있는 방법이 해당 메소드를 반환하는 형식의 재귀로 가능하다고 해서 위와 같이 구현했었어요.

재귀로 구현하면 잘못 작성된 코드일 경우 스택이 무한하게 쌓이는 문제가 발생할 수 있는 것으로 아는데, 혹시 다른 문제점도 존재하나요??

2019-12-31 02:41 UTC, lxxjn0 commented on src/main/java/POS.java
> +    private final List<Function> functions = new ArrayList<>();
다시 생각해보니 Map이 훨씬 합리적인 코드같아요!!

2019-12-31 02:46 UTC, lxxjn0 commented on src/main/java/domain/Payment/OrderAmount.java
> +    public static OrderAmount ZERO = new OrderAmount(ZERO_ORDER_AMOUNT);
이번 프리코스를 진행하면서 받은 피드백 중에서 이런 식으로 작성한 코드를 보내주셨었어요.

```java
public class Score {
		private static final int SCORE_MIN = 0;
		private static final int BLACKJACK_SCORE = 21;
		private static final int TEN = 10;

		public static final Score ZERO = new Score(0);

		private final int score;

		public Score(int score) {
				if (score < SCORE_MIN) {
						throw new IllegalArgumentException("점수는 0이상이어야 합니다.");
				}
				this.score = score;
		}
		...
}
```

피드백을 확인하면서 공부를 진행하다가 해당 코드를 보고 'ZERO같은 상수는 해당 객체의 클래스(만약 Score라는 객체에 해당하는 ZERO상수라면 Score 클래스)에서 선언해야 하구나' 하고 위와 같이 작성했었는데 자주 사용되는 클래스에서 선언하는 방식이 좀 더 나을까요?

2019-12-31 02:47 UTC, lxxjn0 commented on src/main/java/domain/function/Function.java
> +public class Function {
안그래도 아직 Java의 객체지향에 대해 어색한 부분이 많아서 더 공부를 해볼게요!!!

2019-12-31 04:13 UTC, lxxjn0 commented on src/main/java/domain/function/OrderFunction.java
> +        OutputView.printTables(tables);
안그래도 MVC 패턴을 적용해보고 싶었는데 해당 패턴을 공부하고 적용할 수 있는 능력까지 갖추기엔 시간이 부족해서 적용시키질 못했네요. 한번 찾아보면서 공부를 다시 진행해볼게요!!

2019-12-31 04:13 UTC, lxxjn0 commented on src/main/java/domain/function/OrderFunction.java
> +                .get();
넵!! 감사합니다 👍

2019-12-31 04:16 UTC, lxxjn0 commented on src/main/java/domain/table/Table.java
> +    private OrderAmount orderAmount = OrderAmount.ZERO;
아직 제가 이런 변수를 생성자에서 초기화하는게 맞는건지, 아니면 선언하면서 초기화하는게 맞는건지가 헛갈리더라고요.

![image](https://user-images.githubusercontent.com/48052622/71609918-9702f700-2bcf-11ea-9aed-3ce5d34c1a83.png)

위의 코드가 이번 프리코스 블랙잭 미션에서 미리 주어진 코드인데, 해당 코드에서 생성자에 초기화를 진행하여서 저도 위와 같은 형식으로 진행하였어요.
따로 배운적이 없어서 최대한 프리코스의 미션을 참고자료 삼아 진행했는데 혹시 제가 학습할 만한 자료가 있다면 여쭤봐도 괜찮을까요??

2019-12-31 04:18 UTC, lxxjn0 commented on src/main/java/view/OutputView.java
> +    private static final String NON_COMPLETE_PAYMENT_BOTTOM_LINE = "└ \\ ┘";
너무 급하고 정신이 없어서 위 코드를 제대로 확인하질 못했네요... ㅠㅠ
완전 놓쳤던 부분인데 감사합니다!

2020-01-02 13:17 UTC, TheDevLuffy commented on src/main/java/Application.java
> +            return getInputFunctionNumber();
``재귀로 구현하면 잘못 작성된 코드일 경우 스택이 무한하게 쌓이는 문제`` 가 발생할 수 있다는 점을 짚고 넘어가시면 좋을 것 같아서 위와 같은 리뷰를 남겨드렸어요 ㅎㅎ

2020-01-02 13:20 UTC, TheDevLuffy commented on src/main/java/domain/Payment/OrderAmount.java
> +    public static OrderAmount ZERO = new OrderAmount(ZERO_ORDER_AMOUNT);
``ZERO`` 변수가 한 곳에서만 사용 되고 있고, 코드를 구현 하면서 고민해볼 수 있는 부분이라고 생각하여 위와 같은 코멘트를 남겨 보았습니다 🤠

2020-01-02 13:24 UTC, TheDevLuffy commented on src/main/java/domain/table/Table.java
> +    private OrderAmount orderAmount = OrderAmount.ZERO;
코멘트를 달아드리면서 말씀드린 것 처럼 저의 코멘트는 참고용 이예요 ㅎㅎ
**개인적**으로 필드에서 초기화(캡쳐해주신 사진처럼) 보다
생성자에서 초기화를 동시에 진행(아래의 코드 블록처럼)하는 것이 코드를 읽기 좋다고 생각하여 코멘트를 남겨보았어요.
```java
public class Player {
    private final String name;
    private final double bettingMoney;
    private final List<Card> cards;

    public Player(String name, double bettingMoney) {
        this.name = name;
        this.bettingMoney = bettingMoney;
        this.cards = new ArrayList<>();
    }

    // ...
}
```

2020-01-02 13:28 UTC, TheDevLuffy commented on src/main/java/domain/table/Table.java
> +    private OrderAmount orderAmount = OrderAmount.ZERO;
이전 리뷰에서 말씀 드렸던 것 처럼 코드 구현에는 정답이 없다는 것을 참고해주세요~
**개인적**으로 위의 사진처럼 필드에서 초기화 하는 방법보다 아래의 코드 블록처럼 생성자에서 초기화 해주는 것이 더 읽기 좋다고 생각하여 남겨드린 코멘트 였습니다. ㅎㅎ

```java
public class Player {
    private final String name;
    private final double bettingMoney;
    private final List<Card> cards;

    public Player(String name, double bettingMoney) {
        this.name = name;
        this.bettingMoney = bettingMoney;
        this.cards = new ArrayList<>();
    }
    // ...
}
```

2020-02-11 08:00 UTC, closed without merging